version: '3'

services:
  ktor-server:
    image: openjdk:11-jre-slim
    volumes:
      - ./ktor-server:/app
    working_dir: /app
    command: java -jar ktor-server.jar
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
