version: '3'

services:
  social_network_api:
    image: social-network:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /media/HDD/Docker/teamcity/socialnetwork/mongo:/data/db
